#!/usr/bin/env bash
# Write/refresh TOOL_VERSIONS.md from currently installed binaries.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/project/results/gene_curator_probe/TOOL_VERSIONS.md}"
export PATH="${HOME}/miniconda3/envs/synvoy_env/bin:${PATH}"

mp=$(miniprot --version 2>&1 | head -1 || echo unknown)
mm=$(mmseqs version 2>&1 | head -1 || echo unknown)
iq=$(iqtree2 --version 2>&1 | head -1 || iqtree -version 2>&1 | head -1 || echo unknown)
st=$(samtools --version 2>&1 | head -1 || echo unknown)
ht=$(samtools --version 2>&1 | awk '/htslib/{print $2; exit}')
mf=$(mafft --version 2>&1 | head -1 || echo unknown)
bp=$(python3 -c "import Bio; print(Bio.__version__)" 2>/dev/null || echo unknown)
py=$(python3 -V 2>&1 || echo unknown)

cat > "$OUT" <<EOF
# Pinned tool versions (reproducibility)

Auto-generated by \`scripts/write_tool_versions.sh\` on $(date -u +%Y-%m-%dT%H:%MZ).

| Tool | Version | Notes |
|------|---------|--------|
| miniprot | ${mp} | genome-direct CDS mapping |
| MMseqs2 | ${mm} | identities / homology searches |
| IQ-TREE | ${iq} | phylogeny |
| samtools | ${st} | faidx + region extract |
| htslib | ${ht:-unknown} | with samtools |
| MAFFT | ${mf} | multiple alignment |
| Biopython | ${bp} | translate / SeqIO |
| Python | ${py} | pipeline runners |

## Environment

Preferred conda env: \`synvoy_env\` (\`~/miniconda3/envs/synvoy_env\`).

## Curator acceptance (coordinates committed)

- \`project/results/gene_curator_probe/accepted_curator_loci.csv\`
- per-species \`hits.csv\` + \`present_products.fasta\`
- query pack: \`batch_queries.fasta\`
- innexin refs: \`project/data/references/innexins/\`
EOF

echo "Wrote $OUT"
